// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZOr-BpPELVxt9DXhXOc6tYXKiL9nuDds',
    appId: '1:1007937607264:web:5363a1872da6f970961505',
    messagingSenderId: '1007937607264',
    projectId: 'agroshare-app-2026',
    authDomain: 'agroshare-app-2026.firebaseapp.com',
    storageBucket: 'agroshare-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAAHL0ePohBi3lF4j3-CDhi0zHlJXJw_I',
    appId: '1:1007937607264:android:60c6d35917610561961505',
    messagingSenderId: '1007937607264',
    projectId: 'agroshare-app-2026',
    storageBucket: 'agroshare-app-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0FwP_ShHkkYlT853LTuy3s28apaEr3JI',
    appId: '1:1007937607264:ios:38d51700debba66f961505',
    messagingSenderId: '1007937607264',
    projectId: 'agroshare-app-2026',
    storageBucket: 'agroshare-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.agroshare',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0FwP_ShHkkYlT853LTuy3s28apaEr3JI',
    appId: '1:1007937607264:ios:38d51700debba66f961505',
    messagingSenderId: '1007937607264',
    projectId: 'agroshare-app-2026',
    storageBucket: 'agroshare-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.agroshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZOr-BpPELVxt9DXhXOc6tYXKiL9nuDds',
    appId: '1:1007937607264:web:af1bd107e379f7c7961505',
    messagingSenderId: '1007937607264',
    projectId: 'agroshare-app-2026',
    authDomain: 'agroshare-app-2026.firebaseapp.com',
    storageBucket: 'agroshare-app-2026.firebasestorage.app',
  );
}
